

WINDOW_SIZE = (860, 860)
BLACK = (0, 0, 0)
FPS = 60
ASTEROID_FLYING_SPEED = 5
ASTEROID_ROTATING_SPEED = 5
ASTEROID_T1_SPAWN_PERIOD = 1
ASTEROID_T2_SPAWN_PERIOD = 3
ASTEROID_T3_SPAWN_PERIOD = 9
LASER_FLYING_SPEED = 10 
LASER_SPAWN_PERIOD = 2  
STARSHIP_FLYING_SPEED = 0.2  
STARSHIP_ROTATING_SPEED = 5
